# Generated by Django 5.0.1 on 2024-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='skill',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.ManyToManyField(to='app.skill'),
        ),
    ]
