# Generated by Django 5.0.1 on 2024-01-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_personalinfo_skill_personalinfo_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='skills',
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
